### ISSUE TITLE
flux segfault on alpine linux

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-core#5563]
We are working on getting flux running on alpine linux, and are fairly far along and are now debugging runtime issues (e.g., segfault). It will segfault on a broker start:

```
flux broker
```
Here is the tree for the segfault:

![image](https://github.com/flux-framework/flux-core/assets/814322/aedaeb34-1526-4551-aef4-bcacd76c8d14)

And with more detail:

![image](https://github.com/flux-framework/flux-core/assets/814322/f273ac97-83c4-46d3-ae33-f099aaa4afc5)

![image](https://github.com/flux-framework/flux-core/assets/814322/b836d538-112e-41fd-8cd1-0adc38190845)

And the text only (missing cool colors) version (this include bt and bt full):

```console
Starting program: /usr/local/bin/flux broker
warning: Error disabling address space randomization: Operation not permitted
process 806336 is executing new program: /usr/local/libexec/flux/cmd/flux-broker
[New LWP 806339]
[Detaching after vfork from child process 806340]
[New LWP 806343]
[New LWP 806345]
[New LWP 806351]
[New LWP 806353]
[New LWP 806355]
[New LWP 806360]

Thread 8 "flux-broker-0" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 806360]
hostlist_create_bracketed (hostlist=0x7fb4eaf05410 "0e9d63c215fe", r_op=<synthetic pointer>, sep=0x7fb4eaef7eb5 "\t, ")
    at hostlist.c:487
487	    struct hostlist * new = hostlist_create ();
(gdb) bt
#0  hostlist_create_bracketed (hostlist=0x7fb4eaf05410 "0e9d63c215fe", r_op=<synthetic pointer>, sep=0x7fb4eaef7eb5 "\t, ")
    at hostlist.c:487
#1  0x00007fb4eaef10bc in hostlist_append (hl=0x7fb4eaf05140, hosts=<optimized out>) at hostlist.c:605
#2  0x00007fb4eaee8f5b in rlist_nodelist (rl=0x7fb4eacdf0a0) at rlist.c:1479
#3  0x00007fb4eaee9302 in rlist_json_nodelist (rl=0x7fb4eacdf0a0, result=0x7fb4eab9f3b8) at rlist.c:1570
#4  0x00007fb4eaee9816 in rlist_to_R (rl=0x7fb4eacdf0a0) at rlist.c:1712
#5  0x00007fb4eaedcb05 in topo_reduce_finalize (topo=0x7fb4eaf07000) at topo.c:135
#6  0x00007fb4eaedce76 in topo_reduce (topo=0x7fb4eaf07000) at topo.c:232
#7  0x00007fb4eaedd135 in topo_create (ctx=0x7fb4eacde8d0, no_verify=false, no_restrict=false) at topo.c:310
#8  0x00007fb4eaedbc48 in mod_main (h=0x7fb4eaf01b50, argc=0, argv=0x7fb4eacae4d0) at resource.c:465
#9  0x00005575a15e0b9a in module_thread (arg=0x7fb4eaf45cc0) at module.c:208
#10 0x00007fb4eb856bc2 in ?? () from /lib/ld-musl-x86_64.so.1
#11 0x0000000000000000 in ?? ()
(gdb) bt full
#0  hostlist_create_bracketed (hostlist=0x7fb4eaf05410 "0e9d63c215fe", r_op=<synthetic pointer>, sep=0x7fb4eaef7eb5 "\t, ")
    at hostlist.c:487
        new = <optimized out>
        ranges = <error reading variable ranges (value requires 245760 bytes, which is more than max-value-size)>
        nr = <optimized out>
        rc = <optimized out>
        p = <optimized out>
        tok = <optimized out>
        str = <optimized out>
        orig = <optimized out>
        cur_tok = "\024~\357\352\264\177\000\000\000\344\266\352\264\177\000\000\367\200\357\352\264\177\000\000\000\000\000\000\000\000\000\000p|\265\352\264\177\000\000\016\000\000\000\000\000\000\000\020", '\000' <repeats 14 times>, "9\016\000\000\000\000\000\000\000\345$\205\353\264\177\000\000\000\000\000\000\000\000\000\000\003\000\000\000\000\000\000\000\346\360\271\352\264\177\000\000\370\360\271\352\264\177\000\000\000\360\271\352\264\177\000\000\016\004\205\353\264\177\000\000\000\000\000\000\000\000\000\000\r~\357\352\264\177\000\000p\357\271\352\264\177\000\000\030\000\000\000\000\000\000\0000\000\000\0000\000\000\000h\363\271\352\264\177\000\000p\362\271\352\264\177", '\000' <repeats 34 times>...
#1  0x00007fb4eaef10bc in hostlist_append (hl=0x7fb4eaf05140, hosts=<optimized out>) at hostlist.c:605
        new = <optimized out>
        retval = <optimized out>
#2  0x00007fb4eaee8f5b in rlist_nodelist (rl=0x7fb4eacdf0a0) at rlist.c:1479
        n = 0x7fb4eaf07740
        hl = 0x7fb4eaf05140
#3  0x00007fb4eaee9302 in rlist_json_nodelist (rl=0x7fb4eacdf0a0, result=0x7fb4eab9f3b8) at rlist.c:1570
        hl = 0x4c183cf870d00f6
#4  0x00007fb4eaee9816 in rlist_to_R (rl=0x7fb4eacdf0a0) at rlist.c:1712
        R = 0x0
        R_lite = 0x7fb4eaf05020
        nodelist = 0x0
        properties = 0x0
#5  0x00007fb4eaedcb05 in topo_reduce_finalize (topo=0x7fb4eaf07000) at topo.c:135
        resobj = 0x0
#6  0x00007fb4eaedce76 in topo_reduce (topo=0x7fb4eaf07000) at topo.c:232
        val = 0x7fb4eafd8af0 "0"
#7  0x00007fb4eaedd135 in topo_create (ctx=0x7fb4eacde8d0, no_verify=false, no_restrict=false) at topo.c:310
        topo = 0x7fb4eaf07000
        R = 0x0
        flags = 0
#8  0x00007fb4eaedbc48 in mod_main (h=0x7fb4eaf01b50, argc=0, argv=0x7fb4eacae4d0) at resource.c:465
        ctx = 0x7fb4eacde8d0
--Type <RET> for more, q to quit, c to continue without paging--
        error = {
          text = "07\360\352\264\177\000\000\352(^\241uU\000\000\000\241\177\353\264\177\000\000\350\f\200\353\264\177\000\000\331x\202\353\264\177\000\000ya\202\353\264\177\000\00007\360\352\264\177\000\000P\216\364\352\264\177\000\00007\360\352\264\177\000\000\024dy\353\264\177\000\000\300\\\364\352\264\177\000\000\300\\\364\352\264\177\000\000\300\365\271\352\264\177\000\000\245w\202\353\264\177\000\000\b\000\000\000\000\000\000\000\b\000\000\000\000\000\000\000@\367\271\352\264\177\000\000\220\367\271\352\264\177\000\0008\373\271\352\264\177\000\000\350\f\200\353\264\177\000"}
        exclude_idset = 0x0
        eventlog = 0x0
        monitor_force_up = false
        noverify = false
        norestrict = false
        R_from_config = 0x0
#9  0x00005575a15e0b9a in module_thread (arg=0x7fb4eaf45cc0) at module.c:208
        p = 0x7fb4eaf45cc0
        signal_set = {__bits = {18446744058677166079, 0 <repeats 15 times>}}
        errnum = 0
        uri = '\000' <repeats 127 times>
        av = 0x7fb4eacae4d0
        ac = 0
        mod_main_errno = 0
        msg = 0x0
        f = 0x0
#10 0x00007fb4eb856bc2 in ?? () from /lib/ld-musl-x86_64.so.1
No symbol table info available.
#11 0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by grondo** [comment]
Looks like garbage in the hostname? Can we try a run under valgrind if that's available in case it can catch something going wrong earlier? 
```
$ src/cmd/flux start --wrap=libtool,e.valgrind true
```

**Comment by vsoch** [comment]
That's just what docker container hostnames look like :laughing: 
```
# hostname
0e9d63c215fe
```
I think I'm using libtool wrong.
```
# src/cmd/flux start --wrap=libtool,e.valgrind true
Usage: /opt/spack/opt/spack/linux-alpine3-skylake/gcc-12.2.1/libtool-2.4.7-rduvtm4rruoiaquu2l47htp2msoathy6/bin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: you must specify a MODE
```

I tried this too

```
# src/cmd/flux start --wrap=e.valgrind true
flux-start: error execing broker: No such file or directory
```

**Comment by grondo** [comment]
> That's just what docker container hostnames look like 😆

I was talking about the garbage in `cur_tok` (can't paste it here because it is an image not text.

> libtool:   error: you must specify a MODE

Hm, but we did specify a mode.

You could try:
```
$ src/cmd/flux start --wrap=libtool,execute,valgrind true
```

**Comment by vsoch** [comment]
ohh I see it, the second delimiter is a comma, not a period! This works:

```
0e9d63c215fe:/tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src# src/cmd/flux start --wrap=libtool,e,valgrind true
==806769== Memcheck, a memory error detector
==806769== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==806769== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==806769== Command: /tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/broker/.libs/lt-flux-broker true
==806769== 
==806832== Warning: invalid file descriptor 1048564 in syscall close()
==806832== Warning: invalid file descriptor 1048565 in syscall close()
==806832== Warning: invalid file descriptor 1048566 in syscall close()
==806832== Warning: invalid file descriptor 1048567 in syscall close()
==806832==    Use --log-fd=<number> to select an alternative log fd.
==806832== Warning: invalid file descriptor 1048568 in syscall close()
==806832== Warning: invalid file descriptor 1048569 in syscall close()
==806832== Warning: invalid file descriptor 1048570 in syscall close()
==806769== 
==806769== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==806769==  Bad permissions for mapped region at address 0x5733E68
==806769==    at 0x540E8E6: hostlist_create_bracketed.constprop.0 (hostlist.c:487)
==806769== 
==806769== HEAP SUMMARY:
==806769==     in use at exit: 1,733,502 bytes in 3,460 blocks
==806769==   total heap usage: 14,020 allocs, 10,560 frees, 3,343,335 bytes allocated
==806769== 
==806769== LEAK SUMMARY:
==806769==    definitely lost: 0 bytes in 0 blocks
==806769==    indirectly lost: 0 bytes in 0 blocks
==806769==      possibly lost: 16,589 bytes in 7 blocks
==806769==    still reachable: 1,716,913 bytes in 3,453 blocks
==806769==                       of which reachable via heuristic:
==806769==                         length64           : 248,064 bytes in 178 blocks
==806769==         suppressed: 0 bytes in 0 blocks
==806769== Rerun with --leak-check=full to see details of leaked memory
==806769== 
==806769== For lists of detected and suppressed errors, rerun with: -s
==806769== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)

```

**Comment by grondo** [comment]
> ==806769== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==806769==  Bad permissions for mapped region at address 0x5733E68
==806769==    at 0x540E8E6: hostlist_create_bracketed.constprop.0 (hostlist.c:487)

Well, something very bad is happening there. Do the unit tests in `libhostlist` pass?

**Comment by vsoch** [comment]
> Well, something very bad is happening there. Do the unit tests in libhostlist pass?

Running `make check` now

**Comment by vsoch** [comment]
looks like more issues (not detected on compile) with argz

```
 CC       test/environment_t-environment.o
  CCLD     test_environment.t
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ../../../src/common/libutil/.libs/libutil.a(environment.o): in function `stringify_env_item':
/tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil/environment.c:96: undefined reference to `argz_stringify'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ../../../src/common/libutil/.libs/libutil.a(environment.o): in function `find_env_item':
/tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil/environment.c:77: undefined reference to `argz_next'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ../../../src/common/libutil/.libs/libutil.a(environment.o): in function `environment_push_inner':
/tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil/environment.c:156: undefined reference to `argz_create_sep'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil/environment.c:171: undefined reference to `argz_next'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil/environment.c:185: undefined reference to `argz_add'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil/environment.c:181: undefined reference to `argz_delete'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil/environment.c:183: undefined reference to `argz_insert'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil/environment.c:157: undefined reference to `argz_count'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil/environment.c:165: undefined reference to `argz_insert'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil/environment.c:164: undefined reference to `argz_next'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ../../../src/common/libutil/.libs/libutil.a(environment.o): in function `environment_insert':
/tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil/environment.c:283: undefined reference to `argz_insert'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ../../../src/common/libutil/.libs/libutil.a(environment.o): in function `environment_push_inner':
/tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil/environment.c:190: undefined reference to `argz_insert'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil/environment.c:192: undefined reference to `argz_add'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ../../../src/common/libutil/.libs/libutil.a(environment.o): in function `environment_var_next':
/tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil/environment.c:269: undefined reference to `argz_next'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:1223: test_environment.t] Error 1
make[4]: Leaving directory '/tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil'
make[3]: *** [Makefile:2224: check-am] Error 2
make[3]: Leaving directory '/tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common/libutil'
make[2]: *** [Makefile:1031: check-recursive] Error 1
make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src/common'
make[1]: *** [Makefile:516: check-recursive] Error 1
make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-flux-core-master-2mgs3ecsdvmjqcthktkpodvgzzx6klhn/spack-src/src'
make: *** [Makefile:597: check-recursive] Error 1
```

**Comment by grondo** [comment]
I'm not sure how you got the broker built without argz/envz? Seems like we should first ensure the build succeeds, then the unit tests, then go ahead and test `flux start`. 

I have a feeling supporting non-glibc libc will be quite a project though.

**Comment by vsoch** [comment]
> Seems like we should first ensure the build succeeds, then the unit tests, then go ahead and test flux start.

Agreed, but it did look like the build was successful - we finished with the man pages.

**Comment by vsoch** [comment]
`make and make install worked` and that installed the broker:

```
# flux broker --help
Usage: flux-broker [OPTIONS]...
  -h, --help             Display this message.
  -v, --verbose=[LEVEL]  Be annoyingly informative by degrees
  -S, --setattr=ATTR=VAL Set broker attribute
  -c, --config-path=PATH Set broker config from PATH (default: none)
```
But indeed I didn't run `make check`! We can do that next time around.

**Comment by garlick** [comment]
Apologies maybe the test needs to link with libmissing.la?  (Which contains argz, env).  I will look in the morning.

**Comment by trws** [comment]
Oh man, some of our libs build without complete symbol checking at link time so we probably just didn't see it until load, and we hide everything in the core libs so they wouldn't be usable. Maybe we want to either link libmissing by default or export the symbols in libflux-internal or something?

**Comment by garlick** [comment]
I fixed more stuff this morning.  I'll post my branch as a WIP so we're not duplicating effort.

**Comment by garlick** [comment]
Posted to #5564 

Data point on the segfault: hostlist and rlist unit tests are passing in that branch.

**Comment by vsoch** [comment]
Update from me! The make -> make install works (on its own) for the first time without me needing to tweak things :partying_face: 

I'm still getting a segfault - should I not be?

**Comment by garlick** [comment]
I see the segfault too, running in-tree.

**Comment by garlick** [comment]
Still not passing all the unit tests though so I was going to see if anything non-mundane comes from that.
