### ISSUE TITLE
valgrind: possible leak in kvs.c:relayfence_request_cb

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#825]
While running valgrind on flux session with heavy kvs activity, I noticed the following possible large leak:
```
 ==70376== 426,136 (936 direct, 425,200 indirect) bytes in 13 blocks are definitely lost in loss record 1,227 of 1,230
==70376==    at 0x4C2B974: calloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==70376==    by 0x54CFAF1: ??? (in /usr/lib64/libjson-c.so.2.0.1)
==70376==    by 0x54CFDBA: json_object_new_object (in /usr/lib64/libjson-c.so.2.0.1)
==70376==    by 0x54D1D45: json_tokener_parse_ex (in /usr/lib64/libjson-c.so.2.0.1)
==70376==    by 0x54D26D6: json_tokener_parse_verbose (in /usr/lib64/libjson-c.so.2.0.1)
==70376==    by 0x54D273D: json_tokener_parse (in /usr/lib64/libjson-c.so.2.0.1)
==70376==    by 0xB4C0729: Jfromstr (shortjson.h:306)
==70376==    by 0xB4C0729: relayfence_request_cb (kvs.c:1199)
==70376==    by 0x5083870: dispatch_message (dispatch.c:492)
==70376==    by 0x5083870: handle_cb (dispatch.c:601)
==70376==    by 0x509CF74: ev_invoke_pending (ev.c:3088)
==70376==    by 0x50A00D6: ev_run (ev.c:3488)
==70376==    by 0x50822EC: flux_reactor_run (reactor.c:134)
==70376==    by 0xB4C2537: mod_main (kvs.c:1657)

```

The issue is not exactly obvious in this case (the `in` JSON object clearly has `Jput` called), but I think it may have something to do with the `ops` object returned by `kp_tfence_dec`. The json-c reference counting as objects are appended to the fence object `f->ops` *appears* to be correct, but I don't see where the outer `ops` object is destroyed, so I thought it better to leave this one to someone more familiar with the code.

**Comment by grondo** [comment]
Here's the method I was using to reproduce this issue, I'll keep testing but I'm assuming that the key part of the reproducer are the failed commits the flux-aggregate testing purposefully creates

(The output below is pruned to fit within manageable space)

```sh
$ valgrind --tool=memcheck --leak-check=full --trace-children=yes --trace-children-skip-by-arg=bash,sh src/cmd/flux start -s 4

# Attempt aggregate to `.` to force aggregator "abort" testing:
$ for i in `seq 1 100`; do flux exec -r 0-3 bash -c "flux aggregate . 1"; done

# Normal aggregation 100 times, each to a different key, then unlink `test.` dir
$ for i in `seq 1 100`; do flux exec -r 0-3 bash -c "flux aggregate test.$i 1"; done; flux kvs unlink test

$ exit
# [snip]
==191995== 426,136 (936 direct, 425,200 indirect) bytes in 13 blocks are definitely lost in loss record 1,231 of 1,233
==191995==    at 0x4C2B974: calloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==191995==    by 0x54CFAF1: ??? (in /usr/lib64/libjson-c.so.2.0.1)
==191995==    by 0x54CFDBA: json_object_new_object (in /usr/lib64/libjson-c.so.2.0.1)
==191995==    by 0x54D1D45: json_tokener_parse_ex (in /usr/lib64/libjson-c.so.2.0.1)
==191995==    by 0x54D26D6: json_tokener_parse_verbose (in /usr/lib64/libjson-c.so.2.0.1)
==191995==    by 0x54D273D: json_tokener_parse (in /usr/lib64/libjson-c.so.2.0.1)
==191995==    by 0xB4C0729: Jfromstr (shortjson.h:306)
==191995==    by 0xB4C0729: relayfence_request_cb (kvs.c:1199)
==191995==    by 0x5083870: dispatch_message (dispatch.c:492)
==191995==    by 0x5083870: handle_cb (dispatch.c:601)
==191995==    by 0x509CF74: ev_invoke_pending (ev.c:3088)
==191995==    by 0x50A00D6: ev_run (ev.c:3488)
==191995==    by 0x50822EC: flux_reactor_run (reactor.c:134)
==191995==    by 0xB4C2557: mod_main (kvs.c:1656)

```

**Comment by grondo** [comment]
I tried simplifying the reproducer to just 100 `flux kvs put .=foo` (force invalid commit), and got a different, but possibly related leak reported from valgrind: Hopefully this helps!

```
==16770== 16,344 (1,728 direct, 14,616 indirect) bytes in 24 blocks are definitely lost in loss record 1,178 of 1,213
==16770==    at 0x4C2B974: calloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==16770==    by 0x54CFAF1: ??? (in /usr/lib64/libjson-c.so.2.0.1)
==16770==    by 0x54CFDBA: json_object_new_object (in /usr/lib64/libjson-c.so.2.0.1)
==16770==    by 0xB4BFAF1: copydir (kvs.c:370)
==16770==    by 0xB4C0F05: commit_apply_fence (kvs.c:513)
==16770==    by 0x509CF74: ev_invoke_pending (ev.c:3088)
==16770==    by 0x50A01C8: ev_run (ev.c:3377)
==16770==    by 0x50822EC: flux_reactor_run (reactor.c:134)
==16770==    by 0xB4C2557: mod_main (kvs.c:1656)
==16770==    by 0x40C597: module_thread (module.c:163)
==16770==    by 0x5BFBDC4: start_thread (pthread_create.c:308)
==16770==    by 0x660FCEC: clone (clone.S:113)
==16770==
```

**Comment by garlick** [comment]
Thanks!  I'm looking at this now.

**Comment by garlick** [comment]
I just pushed a fix that would appear to be the culprit, however I haven't yet been able to run the reproducer in my memory limited c9 environment.  @grondo any chance you could give it a quick spin?

**Comment by grondo** [comment]
Yeah, no prob!

**Comment by grondo** [comment]
Hm, I cherry-picked your patch onto my copy of master, and reran the reproducer, but I'm still seeing the memleak reported by valgrind (the first one in this issue, I'm not seeing the second one at this time)

I'll try starting from a new copy just to make sure I'm not doing something wrong.

**Comment by garlick** [comment]
Does the first script actually fail any commits?  It looks like the aggregator prevents the commit to "." from going through.

**Comment by grondo** [comment]
Oh, duh! Yeah, aggregator doesn't make a failed commit. `flux-aggregate` used to cause a failed commit when it attempted to unlink the destination, but since moving to non-directory destination that is no longer true.

Sorry for the wrong info! I don't have any other ideas what is special about flux-aggregate test then!

**Comment by garlick** [comment]
No problem!   I'm hoping my fix takes care of the second case then at least.  It's really that trace that I was following.

**Comment by grondo** [comment]
Yeah, rerunning some further tests, I don't see the second case anymore. However, I am seeing the original case even with just the `flux kvs put .=foo` test.

**Comment by garlick** [comment]
Still not solved.  Adding some notes:

Simplified reproducer:
```
$ valgrind --tool=memcheck --leak-check=full --trace-children=yes --trace-children-skip-by-arg=bash,sh src/cmd/flux start -s4 /bin/true
[snip]
==129222== 226,449 (936 direct, 225,513 indirect) bytes in 13 blocks are definitely lost in loss record 1,185 of 1,186
==129222==    at 0x4C27F6F: calloc (vg_replace_malloc.c:623)
==129222==    by 0x54CB871: json_object_new (json_object.c:178)
==129222==    by 0x54CC61A: json_object_new_object (json_object.c:354)
==129222==    by 0x54CD868: json_tokener_parse_ex (json_tokener.c:294)
==129222==    by 0x54CE54D: json_tokener_parse_verbose (json_tokener.c:162)
==129222==    by 0x54CE5AD: json_tokener_parse (json_tokener.c:150)
==129222==    by 0xAB37556: Jfromstr (shortjson.h:306)
==129222==    by 0xAB37556: relayfence_request_cb (kvs.c:1220)
==129222==    by 0x5081480: dispatch_message (dispatch.c:492)
==129222==    by 0x5081480: handle_cb (dispatch.c:601)
==129222==    by 0x509BB8C: ev_invoke_pending (ev.c:3088)
==129222==    by 0x50A01B9: ev_run (ev.c:3488)
==129222==    by 0x50803F0: flux_reactor_run (reactor.c:134)
==129222==    by 0xAB361BD: mod_main (kvs.c:1677)
[snip]
```

This reproduces on TOSS 2 and TOSS 3, but not on my Ubuntu desktop nor on c9.  Here are some notes on json-c and valgrind versions installed there

| Package  | Ubuntu 16.04.1 LTS | TOSS 2 | TOSS 3 | C9 |
| ------------- | -------------------------- | ----------- | -----------| ---- |
| json-c | 0.11-4ubuntu2 | 0.11-12.el6 | 0.11-4.el7_0 | |
| valgrind | 1:3.11.0-1ubuntu4.1 |  3.8.1-8.el6 and DEG 3.10.1 | 3.10.0-16.el7 | |
